const { writeFileSync } = require('fs');
const { execSync } = require('child_process');
const { join } = require('path');

function getGitSha() {
  try {
    const sha = execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
    return sha;
  } catch (_) {
    return '';
  }
}

function main() {
  const pkg = require('../package.json');
  const version = pkg.version || '1.0.0';
  const gitSha = getGitSha();
  const timestamp = new Date().toISOString();

  const contents = `// Auto-generated by scripts/write-version.js
export const appVersion = '${version}${gitSha ? `+${gitSha}` : ''}';
export const buildTimestamp = '${timestamp}';
export const gitSha = '${gitSha}';
`;

  const outPath = join(__dirname, '..', 'src', 'environments', 'version.ts');
  writeFileSync(outPath, contents, { encoding: 'utf8' });
  console.log(`Wrote version file to ${outPath}: ${version}${gitSha ? ` (${gitSha})` : ''} @ ${timestamp}`);
}

main();


